"""Home-city lookup. Longest-key-first, word-boundary only. No 2-letter traps."""

from __future__ import annotations

import re

TEAM_HOME_CITY: dict[str, str] = {
    "arsenal": "London",
    "chelsea": "London",
    "tottenham": "London",
    "spurs": "London",
    "west ham": "London",
    "crystal palace": "London",
    "fulham": "London",
    "brentford": "London",
    "wimbledon": "London",
    "charlton": "London",
    "millwall": "London",
    "manchester city": "Manchester",
    "manchester united": "Manchester",
    "liverpool": "Liverpool",
    "everton": "Liverpool",
    "newcastle": "Newcastle upon Tyne",
    "sunderland": "Sunderland",
    "aston villa": "Birmingham",
    "birmingham": "Birmingham",
    "wolverhampton": "Wolverhampton",
    "wolves": "Wolverhampton",
    "west bromwich": "West Bromwich",
    "leicester": "Leicester",
    "nottingham": "Nottingham",
    "derby": "Derby",
    "sheffield united": "Sheffield",
    "sheffield wednesday": "Sheffield",
    "leeds": "Leeds",
    "burnley": "Burnley",
    "bolton": "Bolton",
    "blackburn": "Blackburn",
    "brighton": "Brighton",
    "southampton": "Southampton",
    "portsmouth": "Portsmouth",
    "watford": "Watford",
    "luton": "Luton",
    "norwich": "Norwich",
    "ipswich": "Ipswich",
    "coventry": "Coventry",
    "stoke": "Stoke-on-Trent",
    "middlesbrough": "Middlesbrough",
    "swansea": "Swansea",
    "cardiff": "Cardiff",
    "real madrid": "Madrid",
    "atletico madrid": "Madrid",
    "atletico de madrid": "Madrid",
    "getafe": "Madrid",
    "rayo vallecano": "Madrid",
    "barcelona": "Barcelona",
    "espanyol": "Barcelona",
    "valencia": "Valencia",
    "villarreal": "Villarreal",
    "sevilla": "Seville",
    "real betis": "Seville",
    "athletic bilbao": "Bilbao",
    "athletic club": "Bilbao",
    "real sociedad": "San Sebastian",
    "osasuna": "Pamplona",
    "deportivo alaves": "Vitoria-Gasteiz",
    "alaves": "Vitoria-Gasteiz",
    "celta vigo": "Vigo",
    "malaga": "Malaga",
    "granada": "Granada",
    "real valladolid": "Valladolid",
    "cadiz": "Cadiz",
    "almeria": "Almeria",
    "girona": "Girona",
    "las palmas": "Las Palmas",
    "leganes": "Leganes",
    "bayern munich": "Munich",
    "fc bayern": "Munich",
    "bayern": "Munich",
    "borussia dortmund": "Dortmund",
    "rb leipzig": "Leipzig",
    "bayer leverkusen": "Leverkusen",
    "borussia monchengladbach": "Monchengladbach",
    "monchengladbach": "Monchengladbach",
    "eintracht frankfurt": "Frankfurt",
    "sc freiburg": "Freiburg",
    "vfb stuttgart": "Stuttgart",
    "stuttgart": "Stuttgart",
    "wolfsburg": "Wolfsburg",
    "werder bremen": "Bremen",
    "hamburger": "Hamburg",
    "hertha berlin": "Berlin",
    "union berlin": "Berlin",
    "schalke": "Gelsenkirchen",
    "augsburg": "Augsburg",
    "mainz": "Mainz",
    "hoffenheim": "Sinsheim",
    "fc koln": "Cologne",
    "cologne": "Cologne",
    "heidenheim": "Heidenheim",
    "darmstadt": "Darmstadt",
    "juventus": "Turin",
    "torino": "Turin",
    "ac milan": "Milan",
    "inter milan": "Milan",
    "internazionale": "Milan",
    "as roma": "Rome",
    "lazio": "Rome",
    "napoli": "Naples",
    "atalanta": "Bergamo",
    "fiorentina": "Florence",
    "bologna": "Bologna",
    "genoa": "Genoa",
    "sampdoria": "Genoa",
    "udinese": "Udine",
    "cagliari": "Cagliari",
    "sassuolo": "Sassuolo",
    "empoli": "Empoli",
    "lecce": "Lecce",
    "frosinone": "Frosinone",
    "monza": "Monza",
    "hellas verona": "Verona",
    "venezia": "Venice",
    "parma": "Parma",
    "paris saint-germain": "Paris",
    "paris saint germain": "Paris",
    "olympique de marseille": "Marseille",
    "marseille": "Marseille",
    "olympique lyonnais": "Lyon",
    "monaco": "Monaco",
    "stade rennais": "Rennes",
    "lille": "Lille",
    "montpellier": "Montpellier",
    "nantes": "Nantes",
    "strasbourg": "Strasbourg",
    "toulouse": "Toulouse",
    "reims": "Reims",
    "brest": "Brest",
    "auxerre": "Auxerre",
    "angers": "Angers",
    "le havre": "Le Havre",
    "clermont": "Clermont-Ferrand",
    "lorient": "Lorient",
    "saint-etienne": "Saint-Etienne",
    "ajax": "Amsterdam",
    "feyenoord": "Rotterdam",
    "az alkmaar": "Alkmaar",
    "vitesse": "Arnhem",
    "utrecht": "Utrecht",
    "twente": "Enschede",
    "benfica": "Lisbon",
    "sporting cp": "Lisbon",
    "vitoria guimaraes": "Guimaraes",
}


def get_venue_city(home_team_name: str) -> str | None:
    name = (home_team_name or "").lower().strip()
    if not name:
        return None
    if name in TEAM_HOME_CITY:
        return TEAM_HOME_CITY[name]
    # Longest key first so "manchester city" wins over "manchester united" fragments.
    for key, city in sorted(TEAM_HOME_CITY.items(), key=lambda kv: -len(kv[0])):
        if len(key) < 4:
            continue
        if re.search(rf"\b{re.escape(key)}\b", name):
            return city
    return None
